---
title: "Exposé: Market Justice in Health Care:  A 30-Year Study in Chile"
author: "Cristóbal Mejías"
format:
  html:
    theme: [litera, style-dq.scss]
    toc: true
    toc-depth: 3
    toc-title: "Contenidos"
    toc-location: left
    number-sections: true
    smooth-scroll: true
    embed-resources: true
execute:
  echo: true
lang: es
include-in-header:
  text: |
    <style>p { text-align: justify; }</style>

---

<br>

## Pregunta de investigación

**Opción 1:** *¿En qué medida la percepción de meritocracia y la posición socioeconómica explican la aceptación de la desigualdad en salud en Chile, y cómo ha variado esa relación entre 1999 y 2019?*

**Opción 2:** *¿Cómo ha evolucionado la aceptación de la justicia de mercado en la atención de salud en Chile entre 1999 y 2019, y qué papel juegan la percepción de meritocracia y la posición socioeconómica en explicar esa evolución?*

---

<br>

## Objetivos de investigación

**Objetivo general**

Analizar la evolución de la aceptación de la justicia de mercado en la atención de salud en Chile entre 1999 y 2019, examinando el rol de la percepción de meritocracia y la posición socioeconómica como factores explicativos.

---

**Objetivos específicos**

1. **Describir** cómo ha cambiado la distribución de la aceptación de la desigualdad en la atención de salud en Chile a lo largo de las tres olas (1999, 2009, 2019).
2. **Examinar** la relación entre la percepción/preferencia de meritocracia y la aceptación de la justicia de mercado en la atención de salud en cada período.
3. **Analizar** en qué medida la posición socioeconómica se asocia con la aceptación de la desigualdad en la atención de salud
4. **Evaluar** si la relación entre meritocracia, posición socioeconómica y la aceptación de la desigualdad en atención de salud varía según el período histórico considerado.

---

<br>

## Marco Conceptual


1. Market Justice
2. Market Justice en Health Care
3. Meritocracia
4. Percepción de desigualdad
5. Posición Socioeconómica
6. Caso Chileno


---

## Metodología

### Variable Dependiente: MJ Health Care


| Item | 1999 | 2009 | 2019 |
| ------------------| ---- | ---- | ---- |
| ¿Es justo o injusto, correcto o incorrecto, que las personas con ingresos más altos puedan pagar por una mejor atención de salud que las personas con ingresos más bajos? | 10A  | 18A  | 9A   |

---

### Factores Asociados: Meritocracia

<br>

| Componente  | Dimensiones      | Item                                                             | 1999 | 2009 | 2019 |
| ----------- | ---------------- | ---------------------------------------------------------------- | ---- | ---- | ---- |
| Percepción  | Meritocrático    | ¿Qué importancia tiene tener ambición?                           |      | 11D  |      |
| Percepción  | Meritocrático    | ¿Qué importancia tiene el trabajo duro?                          |      | 11E  | 1D   |
| Percepción  | No meritocrático | ¿Qué importancia tiene provenir de una familia adinerada?        | 1A   | 11A  | 1A   |
| Percepción  | No meritocrático | ¿Qué importancia tiene tener padres con un buen nivel educativo? |      | 11B  | 1B   |
| Percepción  | No meritocrático | ¿Qué importancia tiene la raza de una persona?                   |      | 11I  | 1H   |
| Percepción  | No meritocrático | ¿Qué importancia tiene nacer hombre o mujer?                     |      | 11K  | 1J   |
| Percepción  | No meritocrático | ¿Qué tan importante es conocer a las personas adecuadas?         | 1B   | 11F  | 1E   |
| Percepción  | No meritocrático | ¿Qué importancia tiene tener contactos políticos?                |      | 11G  | 1F   |
| Preferencia | Meritocrático    | ¿Qué tan bien realiza su trabajo?                                | 15F  | 22E  | 14D  |
| Preferencia | Meritocrático    | ¿Cuánto se esfuerza en su trabajo?                               |      | 22F  |      |
| Preferencia | No meritocrático | ¿Qué se necesita para mantener a una familia?                    | 15D  | 22C  |      |
| Preferencia | No meritocrático | ¿Tiene la persona hijos a su cargo?                              | 15E  | 22D  | 14C  |
| NA          | NA               | El nivel de responsabilidad que tiene el trabajo                 | 15A  | 22A  | 14A  |

---

### Factores Asociados: Percepción de desigualdad

Desarrollo a partir del salario percibio obrero y gerente

---

### Factores Asociados: Posición Socioeconómica

| Item                            | 1999 | 2009 | 2019 |
| --------------------------------| ---- | ---- | ---- |
| Educación (Universitario/no)    |      |      |      |
| Sexo (hombre/mujer)             |      |      |      |
| Estatus Social Subjetivo        |      |      |      |
| Posición Política [cep]         |      |      |      |
| Ingreso (total_hog/n_hogar) [cep] |      |      |      |


---

### Estrategia Analítica

- Regresión Log (muy de acuerdo + de acuerdo = 1;0)
- Ingreso de olas 2009 y 2019 como variables predictoras



